import './js/show-loader';
import './js/close-tab';
import './js/progress-bar';
import './js/get-posts';
import './js/drag-and-drop';
import './js/carousel';
import './js/show-news-section';
import './js/get-form-data';
import './js/set-system-date';
